edition = "2024"
style_edition = "2024"

group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true


use_field_init_shorthand = true
wrap_comments = true
format_code_in_doc_comments = true
