[package]
name = "jsonmodem"
version = "0.1.0"
edition = "2024"
authors = ["Aaron Friel <mayreply@aaronfriel.com>"]
description = "A streaming, incremental JSON parser"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aaronfriel/jsonmodem"

[features]
default = []
fuzzing = []
serde = []

[dependencies]
ouroboros = { version = "0.18.5", default-features = false }
# The core crate purposely avoids third-party dependencies to ease
# compilation in restricted environments.
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
insta = { version = "1.43.1", features = ["yaml"] }
serde = { version = "1.0", features = ["derive"] }

# Dev-dependencies are kept minimal; external test helpers that required
# additional crates have been disabled (see tests/ directory) so we do not
# need to pull them in here.  `quickcheck` is brought in exclusively for
# property-based tests and is **not** used in the production code path.

quickcheck = "1.0"
rstest = "0.25.0"
quickcheck_macros = "1.1.0"
is_ci = "1.2.0"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
missing_docs = "deny"
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(coverage,coverage_nightly)',
] }

[lints.clippy]
pedantic = "warn"
perf = "deny"
suspicious = "deny"
