name: Benchmarks

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Run benchmarks
        env:
          RUSTFLAGS: "--cfg=bench"
        run: cargo bench --all --workspace --verbose || true # allow non-zero exit due to unsupported benches on stable

