name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: cargo check
        run: cargo check --workspace --all-targets

      - name: cargo test
        run: cargo test --workspace --all-features --verbose

      - name: cargo clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Maturin
        run: pip install maturin

      - name: Build bindings
        run: maturin develop -m crates/jsonmodem-py/Cargo.toml --release

      - name: Python smoke test
        run: |
          pip install pytest
          pytest -q crates/jsonmodem-py/tests
