name: Fuzzing

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # setup + 5 min fuzzing

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust toolchain (nightly)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          componentsa: llvm-tools

      - name: Install LLVM 19 toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release
          # Import the official signing key
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | \
            sudo tee /usr/share/keyrings/llvm.asc
          # Add the apt.llvm.org repo for *this* Ubuntu release
          echo "deb [signed-by=/usr/share/keyrings/llvm.asc] \
            http://apt.llvm.org/$(lsb_release -cs)/ \
            llvm-toolchain-$(lsb_release -cs)-19 main" | \
            sudo tee /etc/apt/sources.list.d/llvm19.list
          sudo apt-get update
          # Install the pieces you need; amend as required
          sudo apt-get install -y clang-19 lldb-19 lld-19 llvm-19-dev

          # (Optional) make Clang 19 the default ‘clang’ on PATH
          sudo update-alternatives --install /usr/bin/clang   clang   /usr/bin/clang-19   100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-19 100

      - name: Cache fuzz corpora and artifacts
        uses: actions/cache@v4
        with:
          path: |
            fuzz/corpus
            fuzz/artifacts
          key: ${{ runner.os }}-cargo-fuzz-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cargo-fuzz-

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz --locked

      - name: Run fuzzer (5 minutes)
        run: |
          cargo fuzz run fuzz_parser -- -max_total_time=300 -exit_on_crash=1

      - name: Upload fuzz artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-artifacts
          path: fuzz/artifacts
