name: Fuzzing

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust toolchain (nightly)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools

      - name: Restore fuzz corpora and artifacts
        id: cache-fuzz-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            fuzz/corpus
            fuzz/artifacts
          key: ${{ runner.os }}-cargo-fuzz-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cargo-fuzz-

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz --locked

      - name: Fuzz (5 000 runs ≈ 5 min on CI)
        run: cargo fuzz run fuzz_parser -- -runs=5000

      - name: Save updated corpora and artifacts
        id: cache-fuzz-save
        if: always() && steps.cache-fuzz-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            fuzz/corpus
            fuzz/artifacts
          key: ${{ steps.cache-fuzz-restore.outputs.cache-primary-key }}

      - name: Upload fuzz artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-artifacts
          path: fuzz/artifacts
